import type { Metadata } from 'next'
import './data-solutions.css'
import DemandChart from '@/components/data-solutions/DemandChart'
import DataRequestForm from '@/components/data-solutions/DataRequestForm'

export const metadata: Metadata = {
  title: 'Data Solutions · Verifiable Environmental Data · Mālama Labs',
  description:
    'License hardware-signed, hyper-local environmental datasets across carbon, climate, insurance, energy, and AI. Verifiable at the source. Delivered by API.',
}

const ICON = {
  climate: <path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z" />,
}

type UseCase = { title: string; body: string; svg: React.ReactNode }

const USE_CASES: UseCase[] = [
  { title: 'Climate Research', body: 'High-fidelity environmental data for climate modeling, extreme-weather tracking, and macro-ecological research.', svg: (<><circle cx="12" cy="12" r="10" /><line x1="2" y1="12" x2="22" y2="12" />{ICON.climate}</>) },
  { title: 'Carbon Accounting', body: 'Hardware-signed proof of carbon removal and localized emissions, registry-compatible for compliance-grade ESG reporting.', svg: (<><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" /><polyline points="14 2 14 8 20 8" /><path d="m9 15 2 2 4-4" /></>) },
  { title: 'Parametric Insurance', body: 'Smart-contract payouts triggered by unalterable, real-time hazard sensors for flood, drought, and wildfire risk.', svg: (<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />) },
  { title: 'Prediction Markets', body: 'Incorruptible real-world data oracles that settle decentralized markets on physical, sensor-verified outcomes.', svg: (<><path d="M12 3v18" /><path d="M5 7h14" /><path d="m19 7 3 7c-2 1.5-4 1.5-6 0z" /><path d="m5 7 3 7c-2 1.5-4 1.5-6 0z" /><path d="M7 21h10" /></>) },
  { title: 'Smart Cities', body: 'Hyper-local air quality, noise, and traffic metrics generated by citizen-operated sensor networks.', svg: (<><rect x="4" y="2" width="16" height="20" rx="2" /><line x1="9" y1="6" x2="9" y2="6" /><line x1="15" y1="6" x2="15" y2="6" /><line x1="9" y1="10" x2="9" y2="10" /><line x1="15" y1="10" x2="15" y2="10" /><line x1="9" y1="14" x2="9" y2="14" /><line x1="15" y1="14" x2="15" y2="14" /><path d="M9 22v-4h6v4" /></>) },
  { title: 'AI Data Centers', body: 'Multimodal edge-device streams and rack-level power telemetry for training and governing localized AI models.', svg: (<><rect x="4" y="4" width="16" height="16" rx="2" /><rect x="9" y="9" width="6" height="6" /><line x1="9" y1="1" x2="9" y2="4" /><line x1="15" y1="1" x2="15" y2="4" /><line x1="9" y1="20" x2="9" y2="23" /><line x1="15" y1="20" x2="15" y2="23" /><line x1="20" y1="9" x2="23" y2="9" /><line x1="20" y1="14" x2="23" y2="14" /><line x1="1" y1="9" x2="4" y2="9" /><line x1="1" y1="14" x2="4" y2="14" /></>) },
  { title: 'Energy Grids', body: 'Real-time production and consumption metrics from Virtual Power Plants to balance decentralized energy loads.', svg: (<polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2" />) },
  { title: 'Precision Agriculture', body: 'Soil moisture, hyper-local rainfall, and crop-health tracking to optimize yield and resource allocation.', svg: (<><path d="M7 20h10" /><path d="M10 20c5.5-2.5.8-6.4 3-10" /><path d="M9.5 9.4c1.1.8 1.8 2.2 2.3 3.7-1.5.2-3-.3-4.2-1.1-1.1-.8-1.8-2.2-2.3-3.7 1.5-.2 3 .3 4.2 1.1z" /><path d="M14.1 6a7 7 0 0 0-1.1 4c1.9-.1 3.3-.6 4.3-1.4 1-1 1.6-2.3 1.7-4.6-2.7.1-4 1-4.9 2z" /></>) },
]

const ADVANTAGES = [
  { title: 'Cryptographic verifiability', body: 'Every data point is signed at the hardware edge in a secure enclave, preventing spoofing and giving smart contracts a record they can trust.' },
  { title: 'Hyper-local granularity', body: 'Citizen-deployed networks reach spatial density that top-down government or corporate sensors cannot match affordably.' },
  { title: 'Cost efficiency', body: 'Buy data directly from the network of hardware operators through programmatic APIs, without legacy broker margins in between.' },
]

const PROCESS = [
  { n: '01', h: 'Define query', p: 'Specify parameters: location radius, sensor type (CO₂, weather, soil), and reading frequency.' },
  { n: '02', h: 'Fund escrow', p: 'Deposit fiat or stablecoins into the network protocol to cover the cost of the requested data stream.' },
  { n: '03', h: 'Network fulfillment', p: 'Decentralized nodes capture, cryptographically sign, and anchor the data to decentralized storage.' },
  { n: '04', h: 'Consume API', p: 'Retrieve normalized, verifiable data directly into your enterprise backend or smart contracts.' },
]

const Svg = ({ children, size = 22, sw = 2 }: { children: React.ReactNode; size?: number; sw?: number }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={sw} strokeLinecap="round" strokeLinejoin="round">{children}</svg>
)

export default function DataSolutionsPage() {
  return (
    <div className="ds-root">
      {/* HERO */}
      <section className="hero">
        <div className="wrap">
          <div className="eyebrow"><span className="live-dot" />Data Solutions · Buyer Portal</div>
          <h1>Verifiable environmental data, <em>signed at the source.</em></h1>
          <p className="lede">License hyper-local datasets generated by a decentralized network of hardware-signed sensors. Every reading is cryptographically signed at the device and anchored on chain, so it is auditable before it ever reaches your application.</p>
          <div className="hero-actions">
            <a href="#request" className="btn btn-primary">Request data access →</a>
            <a href="#process" className="btn btn-ghost">See how it works ↗</a>
          </div>
        </div>
      </section>

      {/* 01 · USE CASES */}
      <section id="use-cases">
        <div className="wrap">
          <div className="section-num">01 · Use Cases</div>
          <h2 className="section-title">One verified data layer. <em>Many markets.</em></h2>
          <p className="section-lede">Organizations across climate, finance, infrastructure, and AI build on crowdsourced, hardware-verified data. The same Proof-of-Truth pipeline serves every sector below.</p>
          <div className="uc-grid">
            {USE_CASES.map((u) => (
              <div className="uc-card" key={u.title}>
                <div className="uc-icon"><Svg>{u.svg}</Svg></div>
                <h3>{u.title}</h3>
                <p>{u.body}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* 02 · ADVANTAGE */}
      <section id="advantage">
        <div className="wrap">
          <div className="section-num">02 · The Buyer Advantage</div>
          <h2 className="section-title">Legacy brokers measure top-down. <em>We measure at the edge.</em></h2>
          <p className="section-lede">Traditional data providers rely on sparse, expensive infrastructure. A decentralized network crowdsources collection through hardware operators, producing higher density, lower latency, and verifiability that legacy feeds cannot offer.</p>
          <div className="adv-grid">
            {ADVANTAGES.map((a) => (
              <div className="adv-card" key={a.title}>
                <div className="adv-check"><Svg size={14} sw={3}><polyline points="20 6 9 17 4 12" /></Svg></div>
                <h3>{a.title}</h3>
                <p>{a.body}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* 03 · MARKET OUTLOOK */}
      <section id="demand">
        <div className="wrap">
          <div className="section-num">03 · Market Outlook</div>
          <h2 className="section-title">Demand for verifiable data, <em>by sector.</em></h2>
          <p className="section-lede">As autonomous systems and smart contracts proliferate, the need for sensor-verified real-world data rises across buyer segments. The figures below are modeled, not measured.</p>
          <DemandChart />
        </div>
      </section>

      {/* 04 · PROCESS */}
      <section id="process">
        <div className="wrap">
          <div className="section-num">04 · Acquisition Process</div>
          <h2 className="section-title">From query to API <em>in four steps.</em></h2>
          <div className="proc-grid">
            {PROCESS.map((s) => (
              <div className="proc-step" key={s.n}>
                <div className="proc-num">{s.n}</div>
                <h3>{s.h}</h3>
                <p>{s.p}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="cta" id="request">
        <div className="wrap">
          <div className="cta-inner">
            <h2>Ready to build on <em>verifiable world data?</em></h2>
            <p className="section-lede" style={{ margin: '0 auto 32px', textAlign: 'center' }}>Request buyer access and our data team will scope datasets, coverage, and API access for your use case.</p>
            <DataRequestForm />
          </div>
        </div>
      </section>
    </div>
  )
}
