'use client'

import { WHITEPAPER_TOC } from './whitepaper-toc'

function TocNav() {
  return (
    <nav className="rounded-2xl border border-gray-800 bg-[#0d1e35]/90 backdrop-blur p-4 xl:sticky xl:top-28">
      <p className="text-xs font-black uppercase tracking-widest text-malama-accent/90 mb-3">On this page</p>
      <ul className="space-y-1.5 text-sm max-h-[70vh] overflow-y-auto pr-1">
        {WHITEPAPER_TOC.map((item) => (
          <li key={item.id}>
            <a
              href={`#${item.id}`}
              className="text-gray-400 hover:text-malama-accent transition-colors block py-0.5 border-l-2 border-transparent hover:border-malama-accent pl-2"
            >
              {item.label}
            </a>
          </li>
        ))}
      </ul>
    </nav>
  )
}

function P({ children }: { children: React.ReactNode }) {
  return <p className="text-gray-300 leading-relaxed text-sm md:text-[15px]">{children}</p>
}

function H3({ children }: { children: React.ReactNode }) {
  return <h3 className="text-lg font-black text-white mt-8 mb-3">{children}</h3>
}

function Table({
  headers,
  rows,
}: {
  headers: string[]
  rows: (string | number)[][]
}) {
  return (
    <div className="overflow-x-auto my-6 rounded-xl border border-gray-800 shadow-inner">
      <table className="w-full text-sm text-left min-w-[480px]">
        <thead>
          <tr className="bg-[#0A1628] text-gray-400 border-b border-gray-800">
            {headers.map((h) => (
              <th key={h} className="px-4 py-3 font-bold whitespace-nowrap">
                {h}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map((row, i) => (
            <tr key={i} className="border-t border-gray-800/80 hover:bg-white/[0.02]">
              {row.map((c, j) => (
                <td key={j} className="px-4 py-2.5 text-gray-300">
                  {c}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}

function CodeBlock({ children }: { children: string }) {
  return (
    <pre className="my-4 p-4 rounded-xl bg-black/40 border border-gray-800 text-xs text-malama-accent/90 font-mono overflow-x-auto whitespace-pre-wrap">
      {children}
    </pre>
  )
}

function Callout({ title, children, variant = 'accent' }: { title?: string; children: React.ReactNode; variant?: 'accent' | 'warning' }) {
  const styles = variant === 'warning'
    ? 'border-amber-500/25 bg-amber-500/5'
    : 'border-malama-accent/25 bg-malama-accent/5'
  const titleColor = variant === 'warning' ? 'text-amber-400' : 'text-malama-accent'
  return (
    <div className={`my-6 rounded-xl border p-4 text-sm ${styles}`}>
      {title && <p className={`font-bold mb-2 ${titleColor}`}>{title}</p>}
      <div className="text-gray-300 leading-relaxed space-y-2">{children}</div>
    </div>
  )
}

export function WhitepaperProse() {
  return (
    <div className="xl:grid xl:grid-cols-[minmax(0,1fr)_200px] xl:gap-10 xl:items-start">
      <div className="xl:hidden mb-8">
        <TocNav />
      </div>
      <article className="prose-docs min-w-0">

        {/* ── 1. Executive Summary ── */}
        <section id="executive-summary" className="scroll-mt-28 mb-16">
          <h2 className="text-2xl font-black text-white mb-4 border-b border-gray-800 pb-2">1. Executive Summary</h2>
          <P>
            MLMA is a utility token designed to coordinate a decentralized climate-data network. It serves four primary functions:
            validator rewards for operators producing and validating SaveCards and compute packets; governance via veMLMA lock with
            PONO credential eligibility; protocol fee payment in MLMA or stablecoin; and incentive alignment through a burn mechanism
            that applies 50% of protocol revenue to permanently remove MLMA from circulation.
          </P>
          <Callout title="Key design principles">
            <ul className="list-disc pl-5 space-y-1.5 text-gray-300">
              <li><strong className="text-white">500M MLMA hard cap.</strong> No additional issuance beyond 500M via governance. Emergency mint would require a hard fork and explicit public disclosure.</li>
              <li><strong className="text-white">Emissions stop after Year 3.</strong> Three-year cold-start only. Years 4 and 5 are revenue-funded with zero further token inflation.</li>
              <li><strong className="text-white">50% burn of protocol revenue.</strong> Permanently removed from circulation. Deflationary pressure scales with network revenue.</li>
              <li><strong className="text-white">1.5× Genesis multiplier in Year 1 only.</strong> Applies to Genesis 200 operators during the bootstrapping phase. Expires at the end of Year 1.</li>
              <li><strong className="text-white">Revenue-first sustainability.</strong> From Year 4, all operator rewards come from protocol fees generated by enterprise data usage.</li>
            </ul>
          </Callout>
        </section>

        {/* ── 2. Token Overview ── */}
        <section id="token-overview" className="scroll-mt-28 mb-16">
          <h2 className="text-2xl font-black text-white mb-4 border-b border-gray-800 pb-2">2. Token Overview</h2>
          <H3>2.1 Name and Ticker</H3>
          <ul className="list-disc pl-5 text-gray-300 space-y-2 text-sm md:text-[15px]">
            <li><strong className="text-white">Name:</strong> Mālama — ʻŌlelo Hawaiʻi (Hawaiian). Meaning: to care for, to tend, to protect, to preserve. The name reflects the company's grounding in place-based stewardship and the mission to make ecological data trustworthy.</li>
            <li><strong className="text-white">Ticker:</strong> MLMA</li>
            <li><strong className="text-white">Precision:</strong> 18 decimals (Cardano native asset standard and ERC-20 compatible)</li>
          </ul>
          <H3>2.2 Primary Functions</H3>
          <Table
            headers={['Function', 'Use Case', 'Recipient']}
            rows={[
              ['Validator rewards', 'Receive MLMA rewards for validating SaveCards and compute packets', 'Network operators'],
              ['Governance (veMLMA)', 'Lock MLMA for DAO voting weight; PONO credential required for eligibility', 'Operators with PONO'],
              ['Fee payment', 'Protocol fees payable in MLMA or stablecoin (operator\'s choice)', 'Protocol treasury'],
              ['Staking rewards', 'Lock as veMLMA for enhanced revenue distributions', 'veMLMA stakers'],
            ]}
          />
          <H3>2.3 Blockchain Architecture</H3>
          <P>MLMA operates across a three-layer architecture, each serving a distinct function:</P>
          <Table
            headers={['Layer', 'Chain', 'Function']}
            rows={[
              ['Primary Archival', 'Cardano', 'Scientific proof, SaveCard custody, MLMA token issuance, 60-second Merkle anchoring via Hex Node quorum. CIP-25/CIP-68 NFT standard.'],
              ['Institutional Settlement', 'Hedera', 'High-throughput settlement for registries, corporate buyers, and prediction market operators. ABFT consensus, deterministic finality.'],
              ['Market Liquidity', 'Base', 'Rewards distribution, governance voting, secondary market liquidity. LayerZero OApp handles cross-chain state synchronization.'],
            ]}
          />
        </section>

        {/* ── 3. Supply Framework ── */}
        <section id="supply-framework" className="scroll-mt-28 mb-16">
          <h2 className="text-2xl font-black text-white mb-4 border-b border-gray-800 pb-2">3. Supply Framework</h2>
          <H3>3.1 Total Supply Cap</H3>
          <P>
            <strong className="text-white">500,000,000 MLMA</strong> — hard ceiling. No additional issuance beyond 500M can occur under any governance vote.
            Emergency issuance would require a hard fork and must be explicitly disclosed as such.
          </P>
          <H3>3.2 Allocation Breakdown</H3>
          <Table
            headers={['Recipient', 'Allocation', 'Tokens', 'Notes']}
            rows={[
              ['Investors (Seed SAFE)', '30%', '150M', 'Per SAFE vesting terms'],
              ['Team and Advisors', '20%', '100M', '4-year vest, 1-year cliff'],
              ['Genesis 200 Operators', '5%', '25M', '125K per operator · $2K entry · 200 nodes'],
              ['Future Network Incentives', '27.5%', '137.5M', 'Y1–Y3 emissions: 79.2M · Uncommitted reserve: 58.3M'],
              ['Protocol Treasury', '17.5%', '87.5M', 'DAO-governed · quarterly reporting required'],
              ['Total', '100%', '500M', 'Hard cap'],
            ]}
          />
          <H3>3.3 Genesis 200 Allocation Detail</H3>
          <P>
            <strong className="text-white">125,000 MLMA per operator.</strong> Entry: $2,000 per node (hardware $380 + geographic hex license $1,620).
            200 nodes total. 195 available to external operators; 5 reserved for Mālama Labs team and production use (Dallas / DFW area).
          </P>
          <P>
            Operators who do not deploy within 90 days of hardware receipt forfeit their geographic license and allocation to the protocol treasury.
          </P>
          <Table
            headers={['Milestone', 'Tokens', 'Timing']}
            rows={[
              ['Hardware boot · deployment registration', '31,250 MLMA (25%)', '~October 2026'],
              ['Months 1–12 linear vesting', '93,750 MLMA (75%)', '~7,813 MLMA/month'],
              ['Month 13 onward', '125,000 MLMA fully vested', 'Hold, stake as veMLMA, or sell'],
            ]}
          />
          <p className="text-xs text-gray-500 italic mt-4">
            Mālama does not publish MLMA price forecasts. Token value is driven by protocol utility and market conditions and may go up or down.
            Participants should not acquire MLMA with the expectation of profit. The Genesis allocation is a fixed participation grant aligned
            with network bootstrapping, subject to vesting to ensure long-term operator alignment.
          </p>
        </section>

        {/* ── 4. Emission Schedule ── */}
        <section id="emission-schedule" className="scroll-mt-28 mb-16">
          <h2 className="text-2xl font-black text-white mb-4 border-b border-gray-800 pb-2">4. Emission Schedule (Years 1–5)</h2>
          <P>Cold-start emissions for three years only. Zero inflation from Year 4, with all rewards funded by protocol revenue.</P>
          <Table
            headers={['Year', 'Emissions', '% of Supply', 'Cumulative', 'Status']}
            rows={[
              ['1', '9.0M MLMA', '1.8%', '9.0M', 'Cold-start · Genesis 1.5× active'],
              ['2', '25.2M MLMA', '5.0%', '34.2M', 'Scaling · Genesis multiplier expires'],
              ['3', '45.0M MLMA', '9.0%', '79.2M', 'Final emission year'],
              ['4', '0', '0%', '79.2M', 'Revenue-funded only'],
              ['5', '0', '0%', '79.2M', 'Revenue-funded only'],
            ]}
          />
          <P>
            <strong className="text-white">Total Y1–Y3 emissions: 79.2M MLMA</strong> (15.8% of supply).
            Uncommitted network incentive reserve: 58.3M MLMA.
            Years 4–5: zero emissions, all rewards from protocol revenue.
          </P>
          <H3>4.2 Year 1 Distribution Logic</H3>
          <CodeBlock>{`Monthly_Validator_Reward =
  (Emission_Pool / Network_Score) × Operator_Score

Operator_Score   = Geographic_Multiplier
                   × Uptime_Multiplier
                   × Genesis_Multiplier

Network_Score    = Sum of all active validator scores

Where:
  Emission_Pool          = 750,000 MLMA/month (9M ÷ 12)
  Geographic_Multiplier  = 0.5× (urban) to 3.0× (strategic)
  Uptime_Multiplier      = 1.0× baseline to 1.5× at 99.9%+
  Genesis_Multiplier     = 1.5× (Year 1 only · Genesis 200 operators)`}</CodeBlock>
          <Callout>
            <p>
              Rewards are competitive and relative, not fixed. Each operator's monthly reward is their weighted score divided by the sum of
              all active validator scores in the network. As the network grows, individual reward weight adjusts proportionally.
              There are no guaranteed yields or fixed per-node allocations from the emission pool. Actual reward volume depends on
              network size, data inflow, uptime, and geographic position relative to all other active validators.
            </p>
          </Callout>
          <Table
            headers={['Hex type', 'Geo mult.', 'Profile']}
            rows={[
              ['Urban', '0.5×', 'Dense deployment, lower data scarcity premium'],
              ['Suburban', '1.0×', 'Mid-density, baseline validation weight'],
              ['Rural', '1.5×', 'Agricultural, scientific interest zones'],
              ['Frontier', '2.0×', 'Underserved regions, high scientific value'],
              ['Strategic', '3.0×', 'Industrial corridors, AI data centers, coastal wetlands, flood-prone agricultural zones, regulatory-priority areas'],
            ]}
          />
          <p className="text-xs text-gray-500 italic mt-2">
            Geographic multiplier parameters are governance-voted (veMLMA). Mālama does not publish per-hex MLMA-per-month forecasts.
            Actual rewards depend on data inflow, validator set size, and demand ramp.
          </p>
        </section>

        {/* ── 5. Genesis Operator Economics ── */}
        <section id="genesis-economics" className="scroll-mt-28 mb-16">
          <h2 className="text-2xl font-black text-white mb-4 border-b border-gray-800 pb-2">5. Genesis Operator Economics</h2>
          <Callout title="▲ Genesis Phase Economics · Non-Steady-State" variant="warning">
            <p>
              Year 1 reward levels reflect the Genesis bootstrapping phase only. The 1.5× Genesis multiplier, constrained early validator
              competition, and the front-loaded emission pool produce elevated reward weight during network cold-start. These economics
              are intentional and temporary. They are not indicative of steady-state returns. Emissions stop entirely after Year 3.
              Long-term rewards are funded exclusively by protocol revenue from enterprise data usage.
            </p>
          </Callout>
          <P>
            Beyond the 125,000 MLMA allocation, Genesis operators receive MLMA rewards for validating SaveCards and compute packets
            using the formula in Section 4.2. The Genesis 1.5× multiplier applies in Year 1 only; it expires as emissions and revenue
            share mature in Year 2.
          </P>
          <H3>5.1 Two Economic Phases</H3>
          <Table
            headers={['Phase', 'Period', 'Reward source', 'Genesis multiplier']}
            rows={[
              ['Genesis boost', 'Years 1–3', 'Monthly emission pool (750K → 2.1M → 3.75M MLMA/month)', '1.5× in Year 1 only'],
              ['Revenue-funded steady state', 'Years 4–5', '25% of protocol revenue distributed monthly', 'None'],
            ]}
          />
          <H3>5.2 Validator Growth and Per-Node Base Rewards</H3>
          <P>
            The emission pool grows from Year 1 to Year 3 specifically to maintain per-validator base reward weight as the network scales.
            This is a design decision, not coincidence.
          </P>
          <Table
            headers={['Period', 'Monthly pool', 'Approx validators', 'Unweighted base per-validator']}
            rows={[
              ['Y1 early (Genesis only)', '750K MLMA/mo', '200', '3,750 MLMA/mo'],
              ['Y1 mature (+ community)', '750K MLMA/mo', '350–550', '1,364–2,143 MLMA/mo'],
              ['Year 2', '2.1M MLMA/mo', '500–800', '2,625–4,200 MLMA/mo'],
              ['Year 3', '3.75M MLMA/mo', '800–1,200', '3,125–4,688 MLMA/mo'],
              ['Year 4 (revenue)', '~$445K/mo total', '1,000–1,500', '~$297–$445/mo USD'],
              ['Year 5 (revenue)', '~$717K/mo total', '1,200–1,800', '~$398–$598/mo USD'],
            ]}
          />
          <H3>5.3 Reward Scenarios (Mechanics, Not Projections)</H3>
          <Table
            headers={['Scenario', 'Geographic multiplier', 'Relative Year 1 weight', 'Notes']}
            rows={[
              ['Low-demand hex', '0.5×–1.0×', 'Lowest', 'Urban or rural zones with low SaveCard volume'],
              ['Medium-demand hex', '1.0×–2.0×', 'Mid', 'Agricultural or moderately-served regions'],
              ['High-demand hex', '2.0×–3.0×', 'Highest', 'Industrial corridor, AI data center, coastal wetland, flood-prone agricultural zone'],
            ]}
          />
          <p className="text-xs text-gray-500 italic mt-2">
            Mālama does not publish operator cost recovery timelines or USD earnings forecasts. Actual rewards depend on data inflow,
            MLMA market price, and network conditions. For a public comparable, see WeatherXM's historical station economics.
            Operators should model conservative scenarios and consult their own advisors before reserving a node.
          </p>
        </section>

        {/* ── 6. Revenue Model ── */}
        <section id="revenue-sustainability" className="scroll-mt-28 mb-16">
          <h2 className="text-2xl font-black text-white mb-4 border-b border-gray-800 pb-2">6. Revenue Model &amp; Sustainability</h2>
          <P>
            Protocol revenue funds all operator rewards from Year 4 onward. Five active commercial verticals generate protocol fees;
            all operate from the same shared hardware trust stack.
          </P>
          <Callout title="The Revenue Flywheel">
            <div className="flex flex-wrap items-center gap-2 text-xs font-mono">
              {[
                'Enterprise sensors deployed',
                'Increases validated data volume',
                'Attracts enterprise data contracts',
                'Generates protocol revenue',
                'Funds validator rewards',
                'Enables more sensor deployments',
              ].map((step, i, arr) => (
                <span key={step} className="flex items-center gap-2">
                  <span className="bg-gray-800 rounded px-2 py-1 text-gray-300">{step}</span>
                  {i < arr.length - 1 && <span className="text-malama-accent">→</span>}
                </span>
              ))}
            </div>
          </Callout>
          <H3>Year 5 Revenue Target by Stream</H3>
          <Table
            headers={['Revenue stream', 'Year 5 target', 'Source']}
            rows={[
              ['Carbon verification (ERW, Biochar, DAC)', '$10.8M', 'SaveCard validation fees from carbon project operators'],
              ['Energy-market data (AI compute + grid attestation)', '$8.06M', 'Institutional subscriptions for Scope 2 and CFE attestation data'],
              ['Parametric insurance', '$1.8M', 'Data service fee + per-settlement fee'],
              ['LCO₂ settlement', '$1.28M', '0.5–2% fee on LCO₂ → VCO₂ conversion events'],
              ['Prediction market data licensing', '$2.0M', 'Licensing + resolution fees on Kalshi and Polymarket climate markets'],
              ['MRAA-01 SaaS (direct device revenue)', '$10.5M', '$200/rack/yr × ~52,500 deployed AI compute monitoring units'],
              ['Total', '$34.44M', '—'],
            ]}
          />
          <p className="text-xs text-gray-500 italic mt-2">
            The data demand that generates protocol revenue exists outside the token. Sensor operators — carbon project developers, data centers,
            kiln operators — pay SaaS fees to the Mālama network independent of MLMA price. This is the structural departure from
            inflation-dependent DePIN models.
          </p>
        </section>

        {/* ── 7. Burn ── */}
        <section id="burn" className="scroll-mt-28 mb-16">
          <h2 className="text-2xl font-black text-white mb-4 border-b border-gray-800 pb-2">7. Burn Mechanism &amp; Deflation</h2>
          <P>
            Half of all protocol revenue is permanently removed from circulation. Burn volume scales with network revenue and the prevailing
            MLMA market price — higher revenue and/or lower price produces more tokens burned per dollar of revenue.
          </P>
          <CodeBlock>{`Monthly_Burn         = (Protocol_Revenue × 0.50) / MLMA_Spot_Price
Monthly_Distributed  = Protocol_Revenue × 0.50
  → 25% of total revenue → Node Operators (prorated by score)
  → 25% of total revenue → veMLMA Stakers (prorated by lock duration)`}</CodeBlock>
          <P>
            Burned tokens are sent to a null address on Cardano and Base and cannot be recovered. Each burn transaction records:
            date, block height, amount, MLMA spot price at execution, source revenue feed, and transaction hash on both chain explorers.
          </P>
          <P>
            Cumulative deflation depends on network revenue maturity and market conditions and cannot be forecast with precision.
          </P>
        </section>

        {/* ── 8. veMLMA Governance ── */}
        <section id="vemlma" className="scroll-mt-28 mb-16">
          <h2 className="text-2xl font-black text-white mb-4 border-b border-gray-800 pb-2">8. veMLMA Governance</h2>
          <H3>8.1 Lock Tiers</H3>
          <Table
            headers={['Lock duration', 'Vote weight', 'Distribution multiplier']}
            rows={[
              ['3 months', '0.25×', '0.5×'],
              ['6 months', '0.5×', '1.0×'],
              ['12 months', '1.0×', '2.0×'],
              ['24 months', '2.0×', '3.0×'],
            ]}
          />
          <p className="text-xs text-gray-500 italic mt-2">
            Maximum lock duration: 24 months. Lock is non-transferable. Tokens are returned at expiry.
          </p>
          <H3>8.2 PONO: Non-Transferable Eligibility Credential</H3>
          <P>
            PONO is a non-transferable, on-chain credential issued by the Mālama Foundation to operators who have completed KYB verification,
            deployed active hardware, and demonstrated consistent node operation over a qualifying period. PONO is required to participate
            in governance votes. Holding veMLMA alone is not sufficient. This prevents governance capture by token holders with no
            operational stake in the network.
          </P>
          <P>
            PONO is revocable by governance supermajority for operators who violate network rules: data tampering, hardware fraud, or
            prolonged offline status without notification.
          </P>
          <H3>8.3 Governance Scope and Thresholds</H3>
          <Table
            headers={['Decision type', 'Required threshold', 'Timelock']}
            rows={[
              ['Methodology or validator changes', 'More than 50%', '7 days'],
              ['Fee schedule adjustments', 'More than 66% (supermajority)', '14 days'],
              ['Critical economics or treasury', 'More than 66%', '14 days'],
              ['Emergency protocol pause', 'Foundation multisig', '0 days'],
            ]}
          />
        </section>

        {/* ── 9. Risk Analysis ── */}
        <section id="risk" className="scroll-mt-28 mb-16">
          <h2 className="text-2xl font-black text-white mb-4 border-b border-gray-800 pb-2">9. Risk Analysis</h2>
          <div className="space-y-5 text-sm md:text-[15px] text-gray-300">
            <div>
              <p className="font-bold text-white mb-1">Token Price Risk</p>
              <p>MLMA price could decline due to weak demand from carbon and energy buyers, slower-than-forecast network deployment, broader crypto market conditions, or competition. Mitigation: five diversified revenue streams, hard supply cap, burn mechanism, and veMLMA long-term locks align incentives. The emission schedule is fixed and does not respond to price movements — the protocol cannot issue additional tokens to defend price.</p>
            </div>
            <div>
              <p className="font-bold text-white mb-1">Validator Participation Risk</p>
              <p>Operators may not deploy hardware if anticipated rewards appear insufficient. Mitigation: Genesis 1.5× multiplier incentivizes early movers. Geographic tiers ensure frontier operators in high-value zones earn substantially more than the urban baseline. Hardware cost at $380 is low relative to even conservative reward scenarios.</p>
            </div>
            <div>
              <p className="font-bold text-white mb-1">Year 3 to Year 4 Transition Risk</p>
              <p>The most significant structural risk is the transition from Year 3 emissions to Year 4 revenue funding. Year 3 emissions end in December Year 3. Year 4 operator distributions come entirely from protocol revenue ($21.39M forecast). If validator count expands beyond what Year 4 revenue can support, per-validator earnings will decline. Governance should manage validator admission rates in Year 3 to avoid a cliff at the transition point.</p>
            </div>
            <div>
              <p className="font-bold text-white mb-1">Revenue Forecast Risk</p>
              <p>Year 5 protocol revenue of $34.44M depends on successful deployment across all five verticals and market adoption of Mālama-attested data products. Years 1–3 emissions do not require hitting outer-year revenue targets. Years 4–5 scale with actual fees. If Year 5 revenue is 50% of forecast (~$17M), per-validator baseline rewards are approximately $199–$299 per month before multipliers — meaningful but below the base case.</p>
            </div>
          </div>
        </section>

        {/* ── 10. Projections by Year ── */}
        <section id="by-year" className="scroll-mt-28 mb-16">
          <h2 className="text-2xl font-black text-white mb-4 border-b border-gray-800 pb-2">10. Projections by Year (Detailed)</h2>
          <p className="text-xs text-gray-500 italic mb-6">
            Revenue forecasts in this section exist for internal planning and network design purposes. They are not published as
            forward-looking earnings guidance. Any projected dollar figure attributable to Mālama Labs in marketing or media should
            be treated as incorrect. Consult the whitepaper, audit reports, and your own advisors before making participation decisions.
          </p>
          <H3>Year 1</H3>
          <Table
            headers={['Metric', 'Value']}
            rows={[
              ['Network emissions', '9.0M MLMA · 750K/month'],
              ['Validator count (approx)', '200 Genesis + 150–350 community = 350–550 total'],
              ['Entry per node', '$2,000 (hardware $380 + license $1,620)'],
              ['MLMA per Genesis operator', '125,000 (31,250 at boot · 93,750 over 12 months)'],
              ['Genesis multiplier', '1.5× · Year 1 only'],
              ['Burn activity', 'Minimal — revenue insufficient for significant burns in Year 1'],
            ]}
          />
          <H3>Year 2</H3>
          <Table
            headers={['Metric', 'Value']}
            rows={[
              ['Network emissions', '25.2M MLMA · 2.1M/month'],
              ['Validator count', '500–800'],
              ['Genesis multiplier', 'Expired · Year 1 only'],
              ['Reward source', 'Emissions + ramping revenue share'],
            ]}
          />
          <H3>Year 3</H3>
          <Table
            headers={['Metric', 'Value']}
            rows={[
              ['Network emissions', '45.0M MLMA · 3.75M/month · final emission year'],
              ['Validator count', '800–1,200'],
              ['After Year 3', 'Emissions stop entirely · revenue-funded from Year 4'],
            ]}
          />
          <H3>Years 4–5</H3>
          <Table
            headers={['Metric', 'Year 4', 'Year 5']}
            rows={[
              ['Emissions', '0', '0'],
              ['Validators', '1,000–1,500', '1,200–1,800'],
              ['Reward source', 'Protocol revenue only', 'Protocol revenue only'],
              ['Monthly to operators (25% of revenue)', '~$445K total', '~$717K total'],
              ['Per-validator baseline', '~$297–$445/month', '~$398–$598/month'],
              ['Annual burn (50% of revenue)', '~$10.7M in MLMA', '~$17.2M in MLMA'],
            ]}
          />
        </section>

        {/* ── 11. FAQ ── */}
        <section id="faq" className="scroll-mt-28 mb-16">
          <h2 className="text-2xl font-black text-white mb-4 border-b border-gray-800 pb-2">11. Genesis Phase 1 FAQ</h2>
          <div className="space-y-7 text-sm md:text-[15px] text-gray-300">
            <div>
              <p className="font-bold text-white mb-2">What do I actually receive at reservation vs at hardware boot?</p>
              <p>At reservation ($2,000 payment): your NFT-HEX geographic rights object is minted on Cardano and Base. That is your hex cell license and it is yours immediately. Your 125,000 MLMA allocation does not arrive at reservation. It begins vesting at hardware boot in October 2026: 31,250 MLMA (25%) at boot, then approximately 7,813 MLMA per month over 12 months (75%).</p>
            </div>
            <div>
              <p className="font-bold text-white mb-2">What if MLMA price drops significantly?</p>
              <p>The emission schedule is fixed. If price falls, you receive the same number of tokens for the same validation work, which represents less dollar value. The protocol does not issue additional tokens in response to price movements — any statement to that effect is incorrect. Hardware cost ($380) is low enough that even at $0.05/MLMA, monthly validation rewards in a suburban hex recover hardware cost in under two months. The allocation value at $0.05 would be $6,250 versus $25,000 at the $0.20 base case illustrative price.</p>
            </div>
            <div>
              <p className="font-bold text-white mb-2">Can I stake my vesting allocation before it fully unlocks?</p>
              <p>Yes. Any vested MLMA (the 25% at boot plus monthly tranches as they unlock) can be locked immediately as veMLMA. Unvested amounts cannot be staked. veMLMA locks earn enhanced distribution multipliers and PONO-gated governance weight. Locking does not affect the vesting schedule for remaining unvested tokens.</p>
            </div>
            <div>
              <p className="font-bold text-white mb-2">What is PONO?</p>
              <p>PONO is a non-transferable on-chain credential issued by the Mālama Foundation. It certifies that you are a qualified network participant based on KYB completion, active hardware deployment, and operating history. PONO is required to participate in veMLMA governance votes. You do not need PONO to receive validation rewards or your allocation. PONO governance voting goes live post-mainnet launch.</p>
            </div>
            <div>
              <p className="font-bold text-white mb-2">Is MLMA a security?</p>
              <p>MLMA is designed as a utility token: its value derives from use in fee payment, staking, and governance. Whether it constitutes a security under the Howey test or equivalent frameworks depends on facts and circumstances specific to how it is offered, marketed, and traded. Beneficial Technology is conducting a Howey test analysis that must be complete before any public token offering. This whitepaper does not constitute a representation of regulatory status in any jurisdiction. Consult qualified legal counsel before making any participation decision.</p>
            </div>
            <div>
              <p className="font-bold text-white mb-2">What happens in Year 4 when emissions stop?</p>
              <p>All operator rewards come from 25% of protocol revenue distributed monthly. The other 50% is burned permanently; 25% goes to veMLMA stakers. At the Year 4 revenue forecast of $21.39M, the monthly operator distribution pool is approximately $445,000 total across all active validators, before geographic and uptime multipliers. Validators in high-value zones with long veMLMA locks earn meaningfully above the baseline.</p>
            </div>
          </div>
        </section>

        {/* ── 12. Appendices ── */}
        <section id="appendices" className="scroll-mt-28 mb-20">
          <h2 className="text-2xl font-black text-white mb-4 border-b border-gray-800 pb-2">12. Appendices</h2>
          <div className="space-y-3">
            <details className="group rounded-xl border border-gray-800 bg-[#0d1e35] open:border-malama-accent/30">
              <summary className="cursor-pointer px-4 py-3 font-bold text-white list-none flex justify-between items-center">
                Appendix A — Emission Curve Summary
                <span className="text-gray-500 text-xs group-open:rotate-180 transition-transform">▼</span>
              </summary>
              <div className="px-4 pb-4">
                <CodeBlock>{`Year 1: 9.0M MLMA · 750K/month · linear
Year 2: 25.2M MLMA · 2.1M/month · linear
Year 3: 45.0M MLMA · 3.75M/month · linear (final)
Years 4–5: 0 MLMA

Total Y1–Y3: 79.2M MLMA
Uncommitted reserve: 58.3M MLMA
Hard cap: 500M MLMA`}</CodeBlock>
              </div>
            </details>
            <details className="group rounded-xl border border-gray-800 bg-[#0d1e35]">
              <summary className="cursor-pointer px-4 py-3 font-bold text-white list-none flex justify-between items-center">
                Appendix B — Revenue Assumptions (High Level)
                <span className="text-gray-500 text-xs group-open:rotate-180 transition-transform">▼</span>
              </summary>
              <div className="px-4 pb-4 text-sm text-gray-400 space-y-3 pt-2">
                <p><strong className="text-gray-300">Carbon verification:</strong> 500–1,000 carbon projects using Mālama sensor infrastructure. $100–$1,000/cycle per project. Isometric and Puro.earth as primary registry integrations. Begins Year 1 from ERW and Biochar pilots.</p>
                <p><strong className="text-gray-300">Energy-market data:</strong> 50–200 institutional subscribers (AI hyperscalers, colocation operators, grid analytics firms). $10,000–$200,000/year per subscription. Primary driver: CSRD compliance and 24/7 CFE matching. Begins Year 2 when MRAA-01 is generally available.</p>
                <p><strong className="text-gray-300">Parametric insurance:</strong> 5–50 active parametric products using Mālama data as oracle. Revenue is data service fee plus per-settlement fee.</p>
                <p><strong className="text-gray-300">LCO₂ settlement:</strong> 0.5–2% transaction fee on LCO₂ to VCO₂ conversion events. Scales with pre-financed project volume.</p>
                <p><strong className="text-gray-300">Prediction market data:</strong> Licensing and resolution fees on Kalshi and Polymarket climate markets. Active from Year 1 as SaveCards accumulate on-chain.</p>
                <p><strong className="text-gray-300">MRAA-01 SaaS:</strong> $200/rack/year. Conservative 52,500 racks deployed by Year 5 (approximately 5% penetration of addressable hyperscaler rack base).</p>
              </div>
            </details>
            <details className="group rounded-xl border border-gray-800 bg-[#0d1e35]">
              <summary className="cursor-pointer px-4 py-3 font-bold text-white list-none flex justify-between items-center">
                Appendix C — Regulatory Classification
                <span className="text-gray-500 text-xs group-open:rotate-180 transition-transform">▼</span>
              </summary>
              <div className="px-4 pb-4 text-sm text-gray-400 pt-2">
                <p>MLMA is designed as a utility token. Whether it constitutes a security under the Howey test depends on: the manner of offer and sale, marketing representations, secondary market activity, and reasonable expectations of purchasers. Beneficial Technology is conducting this analysis. No offer or sale of MLMA should proceed in the US without that analysis being complete and reviewed by qualified securities counsel. EU MiCA requirements apply if MLMA is admitted to trading on regulated EU venues. This appendix is informational only and does not constitute legal advice.</p>
              </div>
            </details>
            <details className="group rounded-xl border border-gray-800 bg-[#0d1e35]">
              <summary className="cursor-pointer px-4 py-3 font-bold text-white list-none flex justify-between items-center">
                Appendix D — Burn Transaction Record Format
                <span className="text-gray-500 text-xs group-open:rotate-180 transition-transform">▼</span>
              </summary>
              <div className="px-4 pb-4 text-sm text-gray-400 pt-2">
                <p>Each burn transaction records on Cardano and Base explorers: date, block height, amount of MLMA burned, MLMA spot price at time of execution (sourced from designated oracle), revenue feed source, receiving null address, and transaction hash.</p>
              </div>
            </details>
            <details className="group rounded-xl border border-gray-800 bg-[#0d1e35]">
              <summary className="cursor-pointer px-4 py-3 font-bold text-white list-none flex justify-between items-center">
                Appendix E — Treasury Governance Limits
                <span className="text-gray-500 text-xs group-open:rotate-180 transition-transform">▼</span>
              </summary>
              <div className="px-4 pb-4 text-sm text-gray-400 space-y-2 pt-2">
                <p><strong className="text-gray-300">Operations and payroll:</strong> up to 40% of treasury annually</p>
                <p><strong className="text-gray-300">Developer grants and ecosystem:</strong> up to 30% of treasury annually</p>
                <p><strong className="text-gray-300">Capital reserve:</strong> up to 30% of treasury annually</p>
                <p><strong className="text-gray-300">Emergency fund:</strong> up to 10% of treasury, accessible only via governance supermajority plus Foundation multisig approval</p>
                <p className="mt-3">Treasury publishes quarterly: balance sheet (MLMA and stablecoin holdings), itemized expenditure report, and proposals for the next quarter. All reports are on-chain or IPFS-anchored.</p>
              </div>
            </details>
          </div>
        </section>

        <footer className="border-t border-gray-800 pt-8 text-xs text-gray-600 space-y-2">
          <p>
            <strong className="text-gray-500">Version 2.0</strong> · April 2026 · Working draft pending Beneficial Technology legal review.
            Not for external distribution without that review complete.
          </p>
          <p>Author: Tyler Malin, CEO &amp; Co-Founder · Mālama Labs, Inc.</p>
          <p>Illustrative only; not legal or investment advice.</p>
        </footer>
      </article>

      <aside className="hidden xl:block">
        <TocNav />
      </aside>
    </div>
  )
}
